source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '~> 3.2.15'
gem 'pg'
gem 'dalli'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'kaminari'
gem 'meta_search'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'quiet_assets'

  # Twitter bootstrap
  gem 'twitter-bootstrap-rails'
  gem 'less-rails'
  gem 'therubyracer'
end

group :development do
  gem 'letter_opener'
  gem 'foldscaf', '~> 2.0.0.rc'
  gem 'magic_encoding'
  gem 'annotate'
  gem 'commands'
  gem 'thin'
end

group :production do
  gem 'exception_notification'
end

# Gemas Rails 4.0
gem 'turbolinks'
gem 'cache_digests'
gem 'strong_parameters'
gem 'routing_concerns'

# Gemas de auxilio
gem 'simple_form'
gem 'cancan', '1.6.9'
gem 'friendly_id'
gem 'squeel'
gem 'RedCloth'
gem 'roadie'
gem 'bullet'
gem 'bourbon'
gem 'rest-client'

# Imágenes
gem 'dragonfly'
gem 'fog', '1.15.0'
gem 'rack-cache', require: 'rack/cache'

# Autenticación
gem 'sorcery', '0.8.2'