source 'https://rubygems.org'

gem 'rails', '~> 3.2.11'
gem 'pg'
gem 'dalli'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'kaminari'
gem 'meta_search'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'twitter-bootstrap-rails'
  gem 'less-rails'
  gem 'therubyracer', '0.10.2'
  gem 'quiet_assets'
end

group :development do
  gem 'letter_opener'
  gem 'foldscaf'
  gem 'magic_encoding'
  gem 'annotate'
end

group :production do
  gem 'thin'
  gem 'foreman'
  gem 'exception_notification', '2.6.1'
end

# Gemas Rails 4.0
gem 'turbolinks'
gem 'cache_digests'
gem 'strong_parameters'
gem 'routing_concerns'

# Gemas de auxilio
gem 'simple_form'
gem 'cancan'
gem 'friendly_id'
gem 'squeel'
gem 'RedCloth'
gem 'roadie'
gem 'bullet'
gem 'bourbon'
gem 'rest-client'
gem 'rack-rewrite'

# Imágenes
gem 'dragonfly'
gem 'fog'
gem 'rack-cache', require: 'rack/cache'

# Autenticación
gem 'sorcery'